apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-java-app
  labels:
    app: k8s-java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s
  template:
    metadata:
      labels:
        app: k8s
    spec:
      containers:
      - name: k8s
        image: xheyi/k8s-java-repo:v1
        ports:
        - containerPort: 8080
